-- CART
CREATE TABLE CART (
    CART_ID VARCHAR(255) PRIMARY KEY,
    CATEGORY VARCHAR(255) NOT NULL,
    CREATE_DATE_TIME TIMESTAMP NOT NULL,
    UPDATE_DATE_TIME TIMESTAMP
);

CREATE TABLE ITEM (
    CART_ID VARCHAR(255) PRIMARY KEY,
    CATEGORY VARCHAR(255) NOT NULL,
    CREATE_DATE_TIME TIMESTAMP NOT NULL,
    UPDATE_DATE_TIME TIMESTAMP
);