-- CART
CREATE TABLE CART (
    CART_ID VARCHAR(255) PRIMARY KEY,
    CATEGORY VARCHAR(255) NOT NULL,
    CREATE_DATE_TIME TIMESTAMP NOT NULL,
    UPDATE_DATE_TIME TIMESTAMP
);

CREATE TABLE ITEM (
    ITEM_ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SPECIFICATION TEXT NOT NULL,
    CREATE_DATE_TIME TIMESTAMP NOT NULL,
    UPDATE_DATE_TIME TIMESTAMP,
    CART_ID VARCHAR(255) NOT NULL,
    FOREIGN KEY (CART_ID) REFERENCES CART(CART_ID)
);